package com.tydic.beijing.billing.interfacex.sendEdm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Jan 07 09:36:35 CST 2013
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://customMail.service.produceemail.jd.com/", name = "CustomMailInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomMailInterface {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "SendMail", targetNamespace = "http://customMail.service.produceemail.jd.com/", className = "com.jd.produceemail.service.custommail.SendMail")
    @ResponseWrapper(localName = "SendMailResponse", targetNamespace = "http://customMail.service.produceemail.jd.com/", className = "com.jd.produceemail.service.custommail.SendMailResponse")
    @WebMethod(operationName = "SendMail")
    public java.lang.String sendMail(
        @WebParam(name = "xmlInfo", targetNamespace = "")
        java.lang.String xmlInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendEmailByXML", targetNamespace = "http://customMail.service.produceemail.jd.com/", className = "com.jd.produceemail.service.custommail.SendEmailByXML")
    @ResponseWrapper(localName = "sendEmailByXMLResponse", targetNamespace = "http://customMail.service.produceemail.jd.com/", className = "com.jd.produceemail.service.custommail.SendEmailByXMLResponse")
    @WebMethod
    public int sendEmailByXML(
        @WebParam(name = "xmlInfo", targetNamespace = "")
        java.lang.String xmlInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendEmailByJson", targetNamespace = "http://customMail.service.produceemail.jd.com/", className = "com.jd.produceemail.service.custommail.SendEmailByJson")
    @ResponseWrapper(localName = "sendEmailByJsonResponse", targetNamespace = "http://customMail.service.produceemail.jd.com/", className = "com.jd.produceemail.service.custommail.SendEmailByJsonResponse")
    @WebMethod
    public int sendEmailByJson(
        @WebParam(name = "jsonInfo", targetNamespace = "")
        java.lang.String jsonInfo
    );
}
